use_frameworks!

platform :ios, '10.0'

target 'JWIndicatorView_Example' do
  pod 'JWIndicatorView', :path => '../'

  target 'JWIndicatorView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
